apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: backend-trigger
spec:
  serviceAccountName: vcs-trigger
  triggers:
    - bindings:
        - ref: backend-trigger
      template:
        name: backend-trigger

