apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: frontend-trigger
spec:
  params:
    - name: source-repo
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: room6-frontend-pipeline-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: room6-frontend-pipeline
        params:
          - name: source-repo
            value: $(tt.params.source-repo)
          - name: app-name
            value: room6-frontend-app
          - name: image-repo
            value: quay.io/nickmerrett/room6-frontend
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi

