apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: frontend-trigger
spec:
  serviceAccountName: vcs-trigger
  triggers:
    - bindings:
        - ref: frontend-trigger
      template:
        name: frontend-trigger

