kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frontend-model-storage 
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 8Gi 
  storageClassName: gold 
